//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterStoreDemo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_THONGKENGAY
    {
        public string MaCTTK { get; set; }
        public string MaThongKe { get; set; }
        public string MaMH { get; set; }
        public int Nhap { get; set; }
        public int Xuat { get; set; }
        public int Ton { get; set; }
        public decimal Thu { get; set; }
        public decimal Chi { get; set; }
    
        public virtual THONGKENGAY THONGKENGAY { get; set; }
        public virtual MATHANG MATHANG { get; set; }
    }
}
