//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterStoreDemo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGBAO
    {
        public string MaThongBao { get; set; }
        public int LoaiThongBao { get; set; }
        public string MaPhieuNhapXuat { get; set; }
        public int DaXem { get; set; }
    }
}
