//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterSaveDemo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_HOADON
    {
        public string MaChiTietHoaDon { get; set; }
        public string MaMH { get; set; }
        public string MaHoaDon { get; set; }
        public int SoLuong { get; set; }
        public decimal DonGiaBan { get; set; }
        public string GhiChu { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual MATHANG MATHANG { get; set; }
    }
}
