//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterSaveDemo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_PHIEUNHAPKHO
    {
        public string MaCTPhieuNK { get; set; }
        public string MaMH { get; set; }
        public decimal DonGiaNhap { get; set; }
        public int SoLuong { get; set; }
        public string MaPhieuNhapKho { get; set; }
    
        public virtual PHIEUNHAPKHO PHIEUNHAPKHO { get; set; }
        public virtual MATHANG MATHANG { get; set; }
    }
}
