//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterSaveDemo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_THEKHO
    {
        public string MaCTTheKho { get; set; }
        public System.DateTime NgayNhapXuat { get; set; }
        public string MaPhieuNhapXuat { get; set; }
        public string DienGiai { get; set; }
        public string MaTheKho { get; set; }
    
        public virtual THEKHO THEKHO { get; set; }
    }
}
