//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterSaveDemo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTBCMODONG
    {
        public string MaBaoCaoMoDong { get; set; }
        public System.DateTime NgayXet { get; set; }
        public int SoLuongSoMo { get; set; }
        public int SoLuongSoDong { get; set; }
        public int ChenhLech { get; set; }
    
        public virtual BAOCAOMODONG BAOCAOMODONG { get; set; }
    }
}
