//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterSaveDemo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAITIETKIEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAITIETKIEM()
        {
            this.BAOCAODOANHSOes = new HashSet<BAOCAODOANHSO>();
            this.BAOCAOMODONGs = new HashSet<BAOCAOMODONG>();
            this.SOTIETKIEMs = new HashSet<SOTIETKIEM>();
        }
    
        public string MaLoaiTietKiem { get; set; }
        public string TenLoaiTietKiem { get; set; }
        public int KyHan { get; set; }
        public double LaiSuat { get; set; }
        public int ThoiGianGuiToiThieu { get; set; }
        public string QuyDinhSoTienRut { get; set; }
        public string DangSuDung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAOCAODOANHSO> BAOCAODOANHSOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAOCAOMODONG> BAOCAOMODONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOTIETKIEM> SOTIETKIEMs { get; set; }
    }
}
