//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterSaveDemo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUDNXUATKHO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUDNXUATKHO()
        {
            this.CT_PHIEUDNXUATKHO = new HashSet<CT_PHIEUDNXUATKHO>();
        }
    
        public string MaPhieuDNXK { get; set; }
        public System.DateTime NgayLap { get; set; }
        public string MaQuay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEUDNXUATKHO> CT_PHIEUDNXUATKHO { get; set; }
        public virtual QUAY QUAY { get; set; }
    }
}
