//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterSaveDemo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUGUI
    {
        public string MaPhieuGui { get; set; }
        public string MaSoTietKiem { get; set; }
        public System.DateTime NgayGui { get; set; }
        public decimal SoTienGui { get; set; }
    
        public virtual SOTIETKIEM SOTIETKIEM { get; set; }
    }
}
