USE QLSieuThi
GO

CREATE TABLE THAMSO
(
	MaThamSo INT NOT NULL PRIMARY KEY,
	TenThamSo NVARCHAR(50) NOT NULL,
	GiaTri MONEY NOT NULL
)
GO

----QUAN LI NGUOI DUNG

CREATE TABLE NHOMNGUOIDUNG
(
	MaNhom INT NOT NULL PRIMARY KEY,
	TenNhom NVARCHAR(50) NOT NULL,
)
GO


CREATE TABLE NGUOIDUNG
(
    MaNguoiDung VARCHAR(10) NOT NULL PRIMARY KEY,
	TenDangNhap VARCHAR(50) NOT NULL,
	MatKhau VARCHAR(50) NOT NULL,
	MaNhom INT NOT NULL FOREIGN KEY REFERENCES NHOMNGUOIDUNG(MaNhom),
	HoTen NVARCHAR(MAX) NOT NULL,
	DiaChi NVARCHAR(MAX) NOT NULL,
	SDT NVARCHAR(MAX) NOT NULL,
	GioiTinh NVARCHAR(MAX) NOT NULL,
)
GO


CREATE TABLE CHUCNANG
(
	MaChucNang INT NOT NULL PRIMARY KEY,
	TenChucNang NVARCHAR(50) NOT NULL,
	TenThanhPhanSuDung NVARCHAR(50) NOT NULL,
)
GO

CREATE TABLE PHANQUYEN
(
	MaNhom INT NOT NULL FOREIGN KEY REFERENCES NHOMNGUOIDUNG(MaNhom),
	MaChucNang INT NOT NULL FOREIGN KEY REFERENCES CHUCNANG(MaChucNang),
	GhiChu NVARCHAR(50),
	PRIMARY KEY(MaNhom,MaChucNang)
)
GO

CREATE TABLE NHACUNGCAP
(
	MaNCC VARCHAR(10) NOT NULL PRIMARY KEY,
	TenNCC NVARCHAR(MAX) NOT NULL,
	DiaChi NVARCHAR(MAX) NOT NULL,
	SDT NVARCHAR(MAX) NOT NULL,
	Fax NVARCHAR(MAX) NOT NULL,
)
GO

CREATE TABLE NHASANXUAT
(
	MaNSX VARCHAR(10) NOT NULL PRIMARY KEY,
	TenNSX NVARCHAR(MAX) NOT NULL,
	DiaChi NVARCHAR(MAX) NOT NULL,
	SDT NVARCHAR(MAX) NOT NULL,
)
GO

CREATE TABLE MATHANG
(
	MaMH VARCHAR(10) NOT NULL PRIMARY KEY,
	TenMH NVARCHAR(MAX) NOT NULL,
	MaNCC VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES NHACUNGCAP(MaNCC),
	MaNSX VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES NHASANXUAT(MaNSX),
	GiaNhap MONEY NOT NULL CHECK (GiaNhap>=0), 
	GiaBan MONEY NOT NULL CHECK (GiaBan>=0), 
	SoLuongTonGian INT NOT NULL,
	DonViTinh NVARCHAR(MAX) NOT NULL,
	HinhAnh NVARCHAR(MAX)
)
GO

CREATE TABLE QUAY
(
	MaQuay VARCHAR(10) NOT NULL PRIMARY KEY,
	TenQuay NVARCHAR(MAX) NOT NULL,
	DangSuDung INT NOT NULL,
)
GO


CREATE TABLE PHIEUXUATKHO
(
	MaPhieuXK VARCHAR(10) NOT NULL PRIMARY KEY,
	NgayLap SMALLDATETIME NOT NULL,
	MaNguoiLap VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES NGUOIDUNG(MaNguoiDung),
	MaQuay VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES QUAY(MaQuay),
	TrangThai INT NOT NULL,
)
GO



CREATE TABLE CT_PHIEUXUATKHO
(
	MaCTPhieuXK VARCHAR(10) NOT NULL PRIMARY KEY,
	MaMH VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES MATHANG(MaMH),
	MaPhieuXK  VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES PHIEUXUATKHO(MaPhieuXK),
	DonGia MONEY NOT NULL CHECK (DonGia>=0), 
	SoLuong INT NOT NULL,
	GhiChu NVARCHAR(50),
)
GO

CREATE TABLE HOADON
(
	MaHoaDon VARCHAR(10) NOT NULL PRIMARY KEY,
	NgayLap SMALLDATETIME NOT NULL,
	ThoiGian TIME (0) NOT NULL,
	MaQuay VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES QUAY(MaQuay),
	TongTien MONEY NOT NULL,
	MaNguoiLap VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES NGUOIDUNG(MaNguoiDung),
)
GO

CREATE TABLE CT_HOADON
(
	MaChiTietHoaDon VARCHAR(10) NOT NULL PRIMARY KEY,
	MaMH VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES MATHANG(MaMH),
	MaHoaDon VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES HOADON(MaHoaDon),
	SoLuong INT NOT NULL,
	DonGiaBan MONEY NOT NULL,
	GhiChu NVARCHAR(50),
)
GO

CREATE TABLE PHIEUNHAPKHO
(
	MaPhieuNhapKho VARCHAR(10) NOT NULL PRIMARY KEY,
	NgayLap SMALLDATETIME NOT NULL,
	MaNCC VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES NHACUNGCAP(MaNCC),
	TongTien MONEY NOT NULL CHECK (TongTien>=0), 
	MaNguoiLap VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES NGUOIDUNG(MaNguoiDung),
	Duyet INT NOT NULL,
)
GO

CREATE TABLE CT_PHIEUNHAPKHO
(
	MaCTPhieuNK  VARCHAR(10) NOT NULL PRIMARY KEY,
	MaMH VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES MATHANG(MaMH),
	DonGiaNhap MONEY NOT NULL,
	SoLuong INT NOT NULL,
	MaPhieuNhapKho VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES PHIEUNHAPKHO(MaPhieuNhapKho)
)
GO

CREATE TABLE THEKHO
(
	MaTheKho VARCHAR(10) NOT NULL PRIMARY KEY,
	NgayLap SMALLDATETIME NOT NULL,
	MaNguoiLap VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES NGUOIDUNG(MaNguoiDung),
	MaMH VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES MATHANG(MaMH),
	SoLuongTonKho INT NOT NULL CHECK (SoLuongTonKho >= 0),
)
GO

CREATE TABLE CT_THEKHO
(
	MaCTTheKho VARCHAR(10) NOT NULL PRIMARY KEY,
	NgayNhapXuat SMALLDATETIME NOT NULL,
	MaPhieuNhapXuat VARCHAR(10) NOT NULL,
	DienGiai NVARCHAR(50),
	MaTheKho VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES THEKHO(MaTheKho),

)
GO

CREATE TABLE THONGKENGAY
(
	MaThongKe VARCHAR(10) NOT NULL PRIMARY KEY,
	Ngay SMALLDATETIME NOT NULL,
)
GO

CREATE TABLE CT_THONGKENGAY
(
	MaCTTK VARCHAR(10) NOT NULL PRIMARY KEY,
	MaThongKe VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES THONGKENGAY(MaThongKe),
	MaMH VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES MATHANG(MaMH),
	Nhap INT NOT NULL CHECK (Nhap >=0),
	Xuat INT NOT NULL CHECK (Xuat >= 0),
	Ton INT NOT NULL CHECK (Ton >= 0),
	Thu MONEY NOT NULL,
	Chi MONEY NOT NULL,
)
GO


CREATE TABLE THONGBAO
(
MaThongBao VARCHAR(10) NOT NULL PRIMARY KEY,
LoaiThongBao INT NOT NULL,
MaPhieuNhapXuat VARCHAR(10) NOT NULL,
DaXem INT NOT NULL,
)
GO




